name: CI
on: [push, pull_request]
jobs:
  cs-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: 8.2
          coverage: none
      - name: install PHP CS Fixer
        run: 'composer install -n --prefer-dist --optimize-autoloader --working-dir=tools/php-cs-fixer'
      - name: 'php-cs-fixer check'
        run: 'tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --diff'
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php-versions:  ['8.1', '8.2', '8.3', '8.4']
    name: tests-${{ matrix.php-versions }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/
          key: composer-${{ matrix.php-versions }}-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-stable
      - name: install prism
        run: curl -L https://raw.githack.com/stoplightio/prism/master/install | sh
      - name: run OpenApi3 prism server
        run: nohup prism mock src/Component/OpenApi3/Tests/client/openapi.yaml -p 4010 &
      - name: run OpenApi2 prism server
        run: nohup prism mock src/Component/OpenApi2/Tests/client/swagger.yaml -p 4011 &
      - name: tests
        run: vendor/bin/phpunit --exclude-group none
  tests-lowest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer-lowest
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/
          key: composer-lowest-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: 8.1
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-lowest --prefer-stable
      - name: install prism
        run: curl -L https://raw.githack.com/stoplightio/prism/master/install | sh
      - name: run OpenApi3 prism server
        run: nohup prism mock src/Component/OpenApi3/Tests/client/openapi.yaml -p 4010 &
      - name: run OpenApi2 prism server
        run: nohup prism mock src/Component/OpenApi2/Tests/client/swagger.yaml -p 4011 &
      - name: tests
        run: vendor/bin/phpunit --exclude-group none
